### ISSUE TITLE
Had to install python2.7 -- created ln for script compatibility

### ISSUE THREAD

**Issue by averyfreeman** [gmasse/gpu-pci-passthrough#11]
Hi

I am running your process on a clean install of 16.04.3. LTS

so far so good until I get to:
```
nice OvmfPkg/build.sh -a X64 -n $(getconf _NPROCESSORS_ONLN)
```

The script in question:
```
/home/avery/src/edk2/BaseTools/BinWrappers/PosixLike/build
```

Looking for python2, so
```
# apt install python2.7
ln -s /usr/bin/python2.7 /usr/bin/python2
```

Continued on... :)

**Comment by gmasse** [comment]
It should work with Python 3 also since this commit: https://github.com/tianocore/edk2/commit/9c2d68c0a29909d23266395fc48d0b81b118e341
